language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-firefoxos-inspired-by-rails-env' ]; then cd .. && eval "mv $currentfolder generator-firefoxos-inspired-by-rails-env" && cd generator-firefoxos-inspired-by-rails-env; fi

